version: '3.8'
services:
  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./laravel-api/public:/var/www/html/public
    depends_on:
      - laravel
      - react
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3

  laravel:
    image: ${LARAVEL_IMAGE}
    volumes:
      - ./laravel-api:/var/www/html
      - laravel_storage:/var/www/html/storage
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    expose:
      - "9000"
    healthcheck:
      test: ["CMD", "php", "artisan", "health:check"]
      interval: 30s
      timeout: 10s
      retries: 3

  react:
    image: ${REACT_IMAGE}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  laravel_storage:
