version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-api/public:/var/www/html/public
    depends_on:
      - laravel
      - react

  laravel:
    image: ${LARAVEL_IMAGE}
    volumes:
      - ./laravel-api:/var/www/html
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
    expose:
      - "9000"

  react:
    image: ${REACT_IMAGE}
