version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
      - react

  laravel:
    image: ghcr.io/${{ github.repository }}/laravel:${{ github.sha }}
    ports:
      - "8000:8000"
    depends_on:
      - react

  react:
    image: ghcr.io/${{ github.repository }}/react:${{ github.sha }}
    ports:
      - "3000:3000"
