version: '3.8'

services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./laravel-api/public:/var/www/html/public
    depends_on:
      - laravel
      - react

  laravel:
    image: ${LARAVEL_IMAGE}
    ports:
      - "8000:8000"
    volumes:
      - ./laravel-api:/var/www/html


  react:
    image: ${REACT_IMAGE}
    ports:
      - "3000:3000"
